### ISSUE TITLE
Vast numbers of canvas elements being created in ending transition

### ISSUE THREAD

**Issue by DabaMcD** [OOPS-Studio/CanvasTextInput#1]
Okay, okay, I know. But I still thought you would appreciate my telling you.

First off, I'm a big fan. I've been watching you since you burst onto the KA scene. I've always been disappointed that you didn't put more of your stuff at github as open source.

Anyway, once a year or so, I visit your website to play Twins, and every time I'm reminded how much worse the website version is than the KA version.

Well today I figured out why, I think. If you open inspect element, you'll see that as soon as the end scene transition starts, a new canvas element gets created with every frame, leading to a painfully slow outro.

Another thing, unrelated -- I've wanted to connect with you for a long time, but you don't have contact info anywhere. I understand the reasons for this, but you should at least have a contact form on your website.

I apologize for making this issue on the wrong project. I did what had to be done.

**Comment by DabaMcD** [comment]
Update: It crashed the tab because the lag was  too intense.

**Comment by OOPS-Studio** [comment]
Thank you for bringing that issue to my attention! I will try to investigate that if I have the time. It shouldn't be too hard a fix. Although I must admit, that game lags either way, haha. It was the first game I ever released outside of Khan Academy so I was still very unsure of how exactly my game was interacting with the browser - and I wouldn't be surprised if I drastically screwed it up in more ways than one. Still, I would like to fix the crashing issue even if the lag has to stay. Thanks again for letting me know about it.
Also I apologize for how absurdly outdated my website is as of now. I haven't touched it or even looked at it in like 2+ years. I really should update it someday but it's not really on my radar for now.

Also yeah, I've generally avoided releasing my work on GitHub unless I start the project with the intention of sharing it. It makes me feel a weird sense of pressure to have my work out for others to see, and so I just keep all my projects to myself unless I'm certain I want to make them public.
Although that being said, the project I'm working on right now (which is coming along very well so far and is looking to be finished soon) is one that I do plan to make public. I won't share too many details here though. Gotta leave the door open for me to abandon it at any moment, hah.

Also sure, I'd love to be in touch! If I may ask, what was your name back in the Khan Academy days?
Sadly, I won't be sharing my contact information publicly. I might create a throwaway email just to use for external contacts, but as of now I have no plans to. But thank you for the suggestion and it is definitely something I will keep in mind.

And no worries at all about creating the issue here. I don't mind at all, and yeah, I didn't really leave you any choice either way, haha.

**Comment by DabaMcD** [comment]
I got you: send to dabamcd@duck.com and I'll get back to you from my real email.

No point communicating more in public, am I right?

**Comment by OOPS-Studio** [comment]
I have fixed the crashing error and the endless creation of canvases. It was an issue with p5.js' resource usage and some simple manual garbage collection did the trick.
